//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdvperso.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rdvperso.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Ajouter {
            get {
                return ResourceManager.GetString("Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        internal static string AjouterCompte {
            get {
                return ResourceManager.GetString("AjouterCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel appointment.
        /// </summary>
        internal static string AnnulerRdv {
            get {
                return ResourceManager.GetString("AnnulerRdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push to call us.
        /// </summary>
        internal static string Appeleznous {
            get {
                return ResourceManager.GetString("Appeleznous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your appointment.
        /// </summary>
        internal static string AppointmentsPage {
            get {
                return ResourceManager.GetString("AppointmentsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a remark ?.
        /// </summary>
        internal static string AppRemarque {
            get {
                return ResourceManager.GetString("AppRemarque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the date and time.
        /// </summary>
        internal static string AvailabilitiesTitre {
            get {
                return ResourceManager.GetString("AvailabilitiesTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Chargement {
            get {
                return ResourceManager.GetString("Chargement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on the cards to edit.
        /// </summary>
        internal static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be connected to the network.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For any information please contact us.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been deleted.
        /// </summary>
        internal static string DeleteCompte {
            get {
                return ResourceManager.GetString("DeleteCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        internal static string Desoler {
            get {
                return ResourceManager.GetString("Desoler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have an account.
        /// </summary>
        internal static string ErrorCompte {
            get {
                return ResourceManager.GetString("ErrorCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no appointment times available for the date selected. Please choose another date..
        /// </summary>
        internal static string ErrorHoraire {
            get {
                return ResourceManager.GetString("ErrorHoraire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have an appointment.
        /// </summary>
        internal static string ErrorRdv {
            get {
                return ResourceManager.GetString("ErrorRdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string HolderAddresse {
            get {
                return ResourceManager.GetString("HolderAddresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        internal static string HolderCP {
            get {
                return ResourceManager.GetString("HolderCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string HolderEmail {
            get {
                return ResourceManager.GetString("HolderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string HolderNom {
            get {
                return ResourceManager.GetString("HolderNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string HolderNumero {
            get {
                return ResourceManager.GetString("HolderNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string HolderPrenom {
            get {
                return ResourceManager.GetString("HolderPrenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string HolderVille {
            get {
                return ResourceManager.GetString("HolderVille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your model.
        /// </summary>
        internal static string HomeModel {
            get {
                return ResourceManager.GetString("HomeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our stores.
        /// </summary>
        internal static string HomeTitre {
            get {
                return ResourceManager.GetString("HomeTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 12, Galaxy S20, iPad mini 4.
        /// </summary>
        internal static string LeModele {
            get {
                return ResourceManager.GetString("LeModele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made with ❤️  by .
        /// </summary>
        internal static string MadeWith {
            get {
                return ResourceManager.GetString("MadeWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MenuAcceuil {
            get {
                return ResourceManager.GetString("MenuAcceuil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string MenuAnotresujet {
            get {
                return ResourceManager.GetString("MenuAnotresujet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call us.
        /// </summary>
        internal static string MenuAppeleznous {
            get {
                return ResourceManager.GetString("MenuAppeleznous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MenuInformations {
            get {
                return ResourceManager.GetString("MenuInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        internal static string MenuMesrendezvous {
            get {
                return ResourceManager.GetString("MenuMesrendezvous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string MenuMonCompte {
            get {
                return ResourceManager.GetString("MenuMonCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        internal static string Merci {
            get {
                return ResourceManager.GetString("Merci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your information.
        /// </summary>
        internal static string ModifierCompte {
            get {
                return ResourceManager.GetString("ModifierCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string ModifierJson {
            get {
                return ResourceManager.GetString("ModifierJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Non {
            get {
                return ResourceManager.GetString("Non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Oui {
            get {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model is not listed, contact us.
        /// </summary>
        internal static string PasModele {
            get {
                return ResourceManager.GetString("PasModele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the repair.
        /// </summary>
        internal static string PrestaTitre {
            get {
                return ResourceManager.GetString("PrestaTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add a user?.
        /// </summary>
        internal static string QuestionAddCompte {
            get {
                return ResourceManager.GetString("QuestionAddCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update your information?.
        /// </summary>
        internal static string QuestionCompte {
            get {
                return ResourceManager.GetString("QuestionCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel your appointment?.
        /// </summary>
        internal static string QuestionRdv {
            get {
                return ResourceManager.GetString("QuestionRdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to permanently delete your account?.
        /// </summary>
        internal static string QuestionSupCompte {
            get {
                return ResourceManager.GetString("QuestionSupCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The appointment has been canceled.
        /// </summary>
        internal static string RdvAnnuler {
            get {
                return ResourceManager.GetString("RdvAnnuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchJson {
            get {
                return ResourceManager.GetString("SearchJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete your account.
        /// </summary>
        internal static string SupprimerCompte {
            get {
                return ResourceManager.GetString("SupprimerCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string SupprimerJson {
            get {
                return ResourceManager.GetString("SupprimerJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string Valider {
            get {
                return ResourceManager.GetString("Valider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to validate.
        /// </summary>
        internal static string ValiderJson {
            get {
                return ResourceManager.GetString("ValiderJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill your information.
        /// </summary>
        internal static string VosInfos {
            get {
                return ResourceManager.GetString("VosInfos", resourceCulture);
            }
        }
    }
}
